services:
  - type: web
    name: movie-theater-booking
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn movie_theater_booking.wsgi:application"